Add branch-restriction policy (#151)
This change set includes a branch restriction policy that will limit what
branches are possible to release to what environments.

It can be added with hamctl like the existing auto-release policy.

$ hamctl policy apply branch-restriction --env prod --branch-regex '^master$'
The branch regex is parsed as a regular expression and must be parsable as such.
Validation is done when applying the policy and when ever it is used.

The mutating release flows are updated to verify if the artifact that is to be
released is allowed.

When applying policies they are cross checked against existing policies to
ensure that there is no conflicts, e.g. an auto-release policy for a branch that
is not allowed by a branch-restriction.

Examples

Apply branch restriction on master for environment prod:

    $ hamctl --service a policy apply branch-restriction --branch-regex 'master' -e prod
    [✓] Applied branch restriction policy 'branch-restriction-prod' to service 'a'

Apply auto release that conflicts with a branch-restriction policy:

    $ hamctl --service a policy apply auto-release -b bran -e staging
    Error: policy conflicts with another policy
    Reference: d5c8664b-8148-4c8f-b320-c8130757a7b4
    Usage:
      hamctl policy apply auto-release [flags]

    Flags:
      -b, --branch string   Branch to auto-release artifacts from
      -e, --env string      Environment to release artifacts to
      -h, --help            help for auto-release

    Global Flags:
          --http-auth-token string   auth token for the http service (default "")
          --http-base-url string     address of the http release manager server (default "https://release-manager.dev.lunarway.com")
          --http-timeout duration    HTTP request timeout (default 2m0s)
          --service string           service name to execute commands for

List policies:

    $ hamctl --service a policy list
    Policies for service a

    Auto-releases:

    ENV      BRANCH     ID
    prod     master     auto-release-master-prod

    Branch restrictions:

    ENV         REGEX      ID
    staging     master     branch-restriction-staging
    dev         dev        branch-restriction-dev